Repository census-instrumentation/opencensus-service, pull requests merged in 2018-12, with the labels that each got.

#244 receiver/opencensus: provide a Start method for both Trace and Metrics
  cmd/ocagent/main.go
  receiver/opencensus/opencensus.go
Labels: cla: yes

#247 README: Update usage commands.
  Makefile
  README.md
Labels: cla: yes, documentation

#249 exporter: add ocagent exporter.
  README.md
  exporter/exporterparser/ocagent.go
  internal/config/config.go
Labels: cla: yes, enhancement

#253 Receive jaeger-agent tchannel on port 14267
  receiver/jaeger/trace_receiver.go
Labels: cla: yes

#261 exporter: rename ocagent -> opencensus
  README.md
  exporter/exporterparser/opencensus.go
  internal/config/config.go
Labels: cla: yes

#268 Update .gitignore
  .gitignore
Labels: cla: yes

#263 Add dynamic support for VERSION and default to latest
  Makefile
  build_binaries.sh
  internal/version/version.go
Labels: cla: yes

#255 Address syntax errors in configuration + refactor
  README.md
  exporter/exporterparser/README.md
  images/opencensus-service-deployment-models.png
  images/opencensus-service.png
  receiver/README.md
Labels: cla: yes

#267 receiver/prometheus: start implementation.
  receiver/prometheus/doc.go
  receiver/prometheus/metrics_receiver.go
  receiver/prometheus/options.go
Labels: cla: yes, metrics

#271 Add support to Zipkin V1
  go.mod
  receiver/zipkin/proto_parse_test.go
  receiver/zipkin/trace_receiver.go
  receiver/zipkin/trace_receiver_test.go
  translator/trace/testdata/zipkin_v1_multiple_batches.json
  translator/trace/testdata/zipkin_v1_single_batch.json
  translator/trace/zipkinv1_to_protospan.go
  translator/trace/zipkinv1_to_protospan_test.go
Labels: cla: yes

#281 Better config naming for collector queue
  README.md
  cmd/occollector/app/builder/builder.go
  cmd/occollector/app/builder/builder_test.go
  cmd/occollector/app/builder/processor_builder.go
  cmd/occollector/app/builder/testdata/queued_exporters.yaml
Labels: cla: yes

#270 Add grpc-gateway for OpenCensus trace receiver
  go.mod
  go.sum
  receiver/jaeger/jaeger_agent_test.go
  receiver/jaeger/trace_receiver_test.go
  receiver/opencensus/octrace/opencensus.go
  receiver/opencensus/opencensus.go
  receiver/opencensus/opencensus_test.go
  receiver/opencensus/options.go
  receiver/testhelper/testhelper.go
Labels: cla: yes

#284 Add basic telemetry to collector
  README.md
  cmd/occollector/app/collector/collector.go
  internal/collector/processor/processor.go
  internal/collector/processor/queued_processor.go
  internal/collector/telemetry/telemetry.go
Labels: cla: yes

#285 Opencensus trace receiver should be enabled by default
  cmd/occollector/app/collector/collector.go
Labels: cla: yes

#282 Adds Batch Queue of Ids (for tail-sampling)
  internal/collector/processor/idbatcher/id_batcher.go
  internal/collector/processor/idbatcher/id_batcher_test.go
Labels: cla: yes
