Repository census-instrumentation/opencensus-service, pull requests merged in 2018-10, with the labels that each got.

#45 exporter: plumbing to glue SpanReceiver with OC exporters
  example/main.go
  exporter/example_test.go
  exporter/exporter.go
  exporter/trace_exporter.go
Labels: cla: yes

#41 Add initial occollector information
  README.md
  image/collector-architecture.png
Labels: cla: yes

#55 README: Add more specification on the first message.
  README.md
Labels: cla: yes, documentation

#50 interceptor/opencensus: support multiplexing in Export
  interceptor/opencensus/opencensus.go
  interceptor/opencensus/opencensus_test.go
Labels: cla: yes

#57 interceptor/opencensus: fix protocol misreadings
  interceptor/opencensus/opencensus.go
  interceptor/opencensus/opencensus_test.go
Labels: cla: yes

#56 README: re-organize the sections.
  README.md
Labels: cla: yes, documentation

#58 Simplify the logic in the opencensus interceptor.
  interceptor/opencensus/opencensus.go
Labels: cla: yes

#48 cmd/ocagent: retrofitted with new protocol
  cmd/ocagent/exporterparser/datadog.go
  cmd/ocagent/exporterparser/exparser.go
  cmd/ocagent/exporterparser/stackdriver.go
  cmd/ocagent/exporterparser/zipkin.go
  cmd/ocagent/main.go
Labels: cla: yes

#62 Add badges for travis, godoc and gitter.
  README.md
Labels: cla: yes

#67 Update Agent implementation graph.
  image/agent-implementation.png
Labels: cla: yes, documentation, enhancement

#68 spanreceiver: update ReceiveSpans to take in a context.Context
  exporter/trace_exporter.go
  interceptor/end_to_end_test.go
  interceptor/opencensus/opencensus.go
  interceptor/opencensus/opencensus_test.go
  spanreceiver/spanreceiver.go
Labels: cla: yes

#69 exporter: add Plugins interface as well as guide
  exporter/plugins.go
  exporter/plugins.md
Labels: cla: yes

#65 interceptor/opencensus: record number of received spans
  cmd/ocagent/main.go
  interceptor/opencensus/observability_test.go
  interceptor/opencensus/opencensus.go
  interceptor/opencensus/opencensus_test.go
  interceptor/opencensus/trace_interceptor.go
  internal/observability.go
Labels: cla: yes

#71 build: added Dockerfile + binaries generator bash script
  .gitignore
  Dockerfile
  build_binaries.sh
Labels: cla: yes

#75 Remove images from repo. Host them on Github instead.
  README.md
  image/agent-architecture.png
  image/agent-implementation.png
  image/collector-architecture.png
Labels: cla: yes, documentation

#77 cmd/ocagent: OpenCensus interceptor bind address configurable via config.yaml
  README.md
  cmd/ocagent/config.go
  cmd/ocagent/config.yaml
  cmd/ocagent/main.go
Labels: cla: yes

#78 exporter.TraceExporter: pass a context into ExportSpanData
  exporter/trace_exporter.go
Labels: cla: yes

#89 interceptor & exporter: fix failed tests that used WithPort.
  exporter/example_test.go
  interceptor/opencensus/observability_test.go
  interceptor/opencensus/opencensus_test.go
Labels: bug, cla: yes

#85 Minor readability improvements
  cmd/ocagent/config.go
  cmd/ocagent/main.go
Labels: cla: yes

#94 exporter: add metrics recording helper for Exporters
  internal/observability.go
Labels: cla: yes

#60 cmd/ocagent: added version command
  README.md
  build_binaries.sh
  cmd/ocagent/cli.go
  cmd/ocagent/main.go
  internal/version/version.go
Labels: cla: yes

#96 README: add table of contents and link items
  README.md
Labels: cla: yes

#97 README: add section for building binaries and Docker image
  README.md
Labels: cla: yes

#98 interceptor/opencensus: fix flaky Observability test
  interceptor/opencensus/observability_test.go
Labels: cla: yes

#101 fixup improper closure usage
  interceptor/opencensus/opencensus.go
Labels: cla: yes

#106 interceptor/opencensus: skip TestEnsureRecordedMetrics
  interceptor/opencensus/observability_test.go
Labels: cla: yes

#102 all: move helper TimeToTimestamp to internal
  interceptor/opencensus/opencensus_test.go
  internal/internal.go
  translator/trace/protospan_to_spandata_test.go
Labels: cla: yes

#105 exporter: remove now-defunct plugins
  exporter/plugins.go
  exporter/plugins.md
Labels: cla: yes

#93 all: move exporterparser out of cmd/ocagent
  cmd/ocagent/config.go
  cmd/ocagent/config.yaml
  cmd/ocagent/exporterparser/exparser.go
  cmd/ocagent/exporterparser/stackdriver.go
  cmd/ocagent/main.go
  example/main.go
  exporter/exporterparser/datadog.go
  exporter/exporterparser/exparser.go
  exporter/exporterparser/stackdriver.go
  exporter/exporterparser/zipkin.go
  exporter/trace_exporter.go
Labels: cla: yes

#107 interceptor/opencensus: temporarily disable TestOCInterceptor_endToEnd
  interceptor/opencensus/opencensus_test.go
Labels: cla: yes

#109 exporter/exporterparse: metrics for exported spans
  exporter/exporterparser/datadog.go
  exporter/exporterparser/exparser.go
  exporter/exporterparser/stackdriver.go
  exporter/exporterparser/zipkin.go
  internal/observability.go
Labels: cla: yes

#114 Update Stackdriver configuration parser enableTraces field
  exporter/exporterparser/datadog.go
  exporter/exporterparser/stackdriver.go
Labels: cla: yes

#116 README: fix Stackdriver trace enabling flag
  README.md
Labels: cla: yes

#110 cmd/ocagent: added zPages for overall ocagent process
  README.md
  cmd/ocagent/config.go
  cmd/ocagent/config.yaml
  cmd/ocagent/main.go
  example/main.go
  interceptor/opencensus/opencensus.go
Labels: cla: yes

#119 interceptor/opencensus: remove redundant OCInterceptor prefix
  interceptor/opencensus/opencensus.go
  interceptor/opencensus/opencensus_test.go
  interceptor/opencensus/options.go
Labels: cla: yes

#118 config.yaml: categorize and reorganize YAML file
  README.md
  cmd/ocagent/config.go
  cmd/ocagent/config.yaml
  exporter/exporterparser/datadog.go
  exporter/exporterparser/stackdriver.go
  exporter/exporterparser/zipkin.go
Labels: cla: yes

#120 interceptor/opencensus: rename OCOption to Option
  interceptor/opencensus/opencensus.go
  interceptor/opencensus/opencensus_test.go
  interceptor/opencensus/options.go
  interceptor/opencensus/trace_interceptor.go
Labels: cla: yes

#122 translator/trace: add an Annotations translator
  translator/trace/protospan_to_spandata.go
Labels: cla: yes

#125 interceptor: start adding metric receiver and interceptor.
  interceptor/interceptor.go
  metricsreceiver/metricsreceiver.go
Labels: cla: yes, metrics, process

#111 interceptor: add zipkin /v2 interceptor
  README.md
  cmd/ocagent/config.go
  cmd/ocagent/config.yaml
  cmd/ocagent/main.go
  exporter/exporterparser/zipkin.go
  interceptor/opencensus/opencensus.go
  interceptor/zipkin/testdata/sample1.json
  interceptor/zipkin/trace_interceptor.go
  interceptor/zipkin/trace_interceptor_test.go
  internal/observability.go
Labels: cla: yes

#140 Enable WIP Tool
  .github/wip.yml
Labels: cla: yes

#143 README: Add a paragraph about Library retries.
  README.md
Labels: cla: yes, documentation

#144 README: slightly reword indefinite retries.
  README.md
Labels: cla: yes, documentation

#139 Add a minimal Makefile and set Travis to use it
  .travis.yml
  Makefile
Labels: cla: yes

#148 Remove extra functions and improve JSON check in tests
  exporter/exporterparser/zipkin.go
  exporter/exporterparser/zipkin_test.go
  interceptor/zipkin/trace_interceptor_test.go
  internal/test_utils.go
  internal/testutils/test_utils.go
Labels: cla: yes

#149 README: fix a link.
  README.md
Labels: cla: yes, documentation

#147 Add a Skeleton for Collector
  Makefile
  cmd/occollector/main.go
Labels: cla: yes
