Repository census-instrumentation/opencensus-service, pull requests merged in 2018-11, with the labels that each got.

#152 document: move the design specs to DESIGN.md.
  DESIGN.md
  README.md
Labels: cla: yes, documentation

#156 Add docker scratch for agent and collector
  .gitignore
  Makefile
  cmd/ocagent/Dockerfile
  cmd/ocagent/config.go
  cmd/ocagent/main.go
  cmd/occollector/Dockerfile
  cmd/occollector/main.go
  exporter/exporterparser/zipkin_test.go
Labels: cla: yes

#160 Clean up and enable golint
  .travis.yml
  Makefile
  cmd/ocagent/config.go
  exporter/exporterparser/datadog.go
  exporter/exporterparser/exparser.go
  exporter/exporterparser/jaeger.go
  exporter/exporterparser/stackdriver.go
  exporter/exporterparser/zipkin.go
  exporter/trace_exporter.go
  interceptor/interceptor.go
  interceptor/opencensus/doc.go
  interceptor/opencensus/opencensus.go
  interceptor/opencensus/options.go
  interceptor/opencensus/trace_interceptor.go
  interceptor/zipkin/trace_interceptor.go
  interceptor/zipkin/trace_interceptor_test.go
  internal/internal.go
  internal/observability.go
  internal/version/version.go
  metricsreceiver/metricsreceiver.go
  spanreceiver/spanreceiver.go
  translator/trace/protospan_to_spandata.go
Labels: cla: yes

#162 fix the logical conflict test for zipkin
  cmd/ocagent/config.go
Labels: cla: yes

#161 go.mod: update all dependencies
  go.mod
  go.sum
Labels: cla: yes

#170 interceptor: rename ocinterceptor to octrace.
  cmd/ocagent/main.go
  cmd/occollector/main.go
  exporter/example_test.go
  interceptor/end_to_end_test.go
  interceptor/octrace/doc.go
  interceptor/octrace/observability_test.go
  interceptor/octrace/opencensus.go
  interceptor/octrace/opencensus_test.go
  interceptor/octrace/options.go
  interceptor/octrace/trace_interceptor.go
Labels: cla: yes, refactor

#155 interceptor/zipkin: add logic to parse from Protobuf
  go.mod
  go.sum
  interceptor/zipkin/proto_parse_test.go
  interceptor/zipkin/trace_interceptor.go
  interceptor/zipkin/trace_interceptor_test.go
  internal/internal_test.go
Labels: cla: yes

#178 all: rename interceptor to receiver
  DESIGN.md
  Dockerfile
  README.md
  cmd/ocagent/cli.go
  cmd/ocagent/config.go
  cmd/ocagent/config.yaml
  cmd/ocagent/main.go
  cmd/occollector/main.go
  exporter/example_test.go
  exporter/exporterparser/zipkin.go
  exporter/exporterparser/zipkin_test.go
  internal/observability.go
  receiver/end_to_end_test.go
  receiver/octrace/doc.go
  receiver/octrace/observability_test.go
  receiver/octrace/opencensus.go
  receiver/octrace/opencensus_test.go
  receiver/octrace/options.go
  receiver/octrace/trace_receiver.go
  receiver/receiver.go
  receiver/zipkin/proto_parse_test.go
  receiver/zipkin/testdata/sample1.json
  receiver/zipkin/trace_receiver.go
  receiver/zipkin/trace_receiver_test.go
Labels: cla: yes

#177 Small README updates
  README.md
Labels: cla: yes

#179 spanreceiver.SpanReceiver->spansink.Sink, metricsreceiver.MetricsReceiver->metricsink.Sink
  cmd/ocagent/main.go
  cmd/occollector/main.go
  exporter/example_test.go
  exporter/trace_exporter.go
  metricsink/sink.go
  receiver/end_to_end_test.go
  receiver/octrace/doc.go
  receiver/octrace/opencensus.go
  receiver/octrace/opencensus_test.go
  receiver/octrace/options.go
  receiver/octrace/trace_receiver.go
  receiver/receiver.go
  receiver/zipkin/trace_receiver.go
  receiver/zipkin/trace_receiver_test.go
  spansink/spansink.go
Labels: cla: yes

#180 Output of ocagent
  README.md
Labels: cla: yes

#172 .travis.yml: move Travis to Go1.11
  .travis.yml
  receiver/zipkin/proto_parse_test.go
Labels: cla: yes

#142 add kafka exporter
  README.md
  cmd/ocagent/config.go
  exporter/exporterparser/kafka.go
  go.mod
  go.sum
Labels: cla: yes

#184 Trace translator from Jaeger Thrift to OC-Proto
  .travis.yml
  go.mod
  go.sum
  translator/trace/jaegerthrift_to_protospan.go
  translator/trace/jaegerthrift_to_protospan_test.go
  translator/trace/testdata/ocproto_batch_01.json
  translator/trace/testdata/ocproto_batch_02.json
  translator/trace/testdata/thrift_batch_01.json
  translator/trace/testdata/thrift_batch_02.json
Labels: cla: yes

#190 translator/trace/jaeger: conservative allocations for only existent fields
  internal/internal.go
  translator/trace/jaegerthrift_to_protospan.go
  translator/trace/jaegerthrift_to_protospan_test.go
Labels: cla: yes

#183 receiver/ocmetrics: start adding OCMetricsReceiver.
  metricsink/sink.go
  receiver/opencensus/ocmetrics/doc.go
  receiver/opencensus/ocmetrics/opencensus.go
  receiver/opencensus/ocmetrics/options.go
  receiver/opencensus/octrace/observability_test.go
  receiver/opencensus/octrace/opencensus.go
  receiver/opencensus/opencensus.go
Labels: cla: yes, metrics, process

#192 receiver/jaeger: implement and hookup Jaeger receiver
  README.md
  cmd/ocagent/config.go
  cmd/ocagent/main.go
  go.mod
  go.sum
  receiver/jaeger/trace_receiver.go
  receiver/jaeger/trace_receiver_test.go
Labels: cla: yes

#195 receiver/ocmetrics: add tests on ocmetrics receiver.
  receiver/opencensus/ocmetrics/opencensus_test.go
Labels: cla: yes, metrics, process

#202 Move span and metrics syncs in the receiver.
  cmd/ocagent/main.go
  exporter/trace_exporter.go
  internal/collector/processor/processor_to_sink.go
  metricsink/sink.go
  receiver/end_to_end_test.go
  receiver/jaeger/trace_receiver.go
  receiver/jaeger/trace_receiver_test.go
  receiver/opencensus/ocmetrics/opencensus.go
  receiver/opencensus/ocmetrics/opencensus_test.go
  receiver/opencensus/ocmetrics/options.go
  receiver/opencensus/octrace/doc.go
  receiver/opencensus/octrace/opencensus.go
  receiver/opencensus/octrace/opencensus_test.go
  receiver/opencensus/octrace/options.go
  receiver/opencensus/opencensus.go
  receiver/receiver.go
  receiver/zipkin/trace_receiver.go
  receiver/zipkin/trace_receiver_test.go
  spansink/spansink.go
Labels: cla: yes

#204 Fix readme to use receivers instead of interceptors.
  README.md
Labels: cla: yes

#205 Setup windows builds and tests.
  appveyor.yml
Labels: cla: yes

#213 receiver/zipkin: consolidate server starting to receiver
  cmd/ocagent/main.go
  exporter/exporterparser/zipkin_test.go
  internal/collector/zipkin/receiver.go
  receiver/zipkin/trace_receiver.go
  receiver/zipkin/trace_receiver_test.go
Labels: cla: yes

#217 DESIGN: rename interceptor to receiver in the graph.
  DESIGN.md
Labels: cla: yes, documentation

#222 Add multi trace/metrics receivers.
  exporter/exporterparser/exparser.go
  internal/internal.go
  receiver/receiver.go
Labels: cla: yes

#223 data: add TraceData and MetricsData.
  data/data.go
Labels: cla: yes, process, refactor

#224 receiver: use TraceData and MetricsData in receivers.
  exporter/trace_exporter.go
  internal/collector/processor/exporter_processor.go
  internal/collector/processor/processor_to_sink.go
  receiver/end_to_end_test.go
  receiver/jaeger/trace_receiver.go
  receiver/jaeger/trace_receiver_test.go
  receiver/opencensus/ocmetrics/opencensus.go
  receiver/opencensus/ocmetrics/opencensus_test.go
  receiver/opencensus/octrace/opencensus.go
  receiver/opencensus/octrace/opencensus_test.go
  receiver/receiver.go
  receiver/zipkin/trace_receiver.go
  receiver/zipkin/trace_receiver_test.go
Labels: cla: yes, process, refactor

#227 test: disable the flaky test for now.
  receiver/opencensus/ocmetrics/opencensus_test.go
Labels: bug, build, cla: yes

#219 metrics/exporter: define MetricsExporter interface.
  exporter/metrics_exporter.go
Labels: cla: yes, metrics, process

#235 exporterparser/zipkin: safely retrieve remoteEndpoint serviceName
  exporter/exporterparser/zipkin.go
  exporter/exporterparser/zipkin_test.go
Labels: cla: yes

#237 cmd/ocagent: remove vestigial code
  cmd/ocagent/proto.go
  cmd/ocagent/proto_test.go
Labels: cla: yes

#234 cmd/ocagent: fix Zipkin logical conflict detection typo
  cmd/ocagent/config.go
  cmd/ocagent/config_test.go
Labels: cla: yes

#221 OC Proto to Jaeger Thrift translation
  go.mod
  go.sum
  receiver/jaeger/trace_receiver_test.go
  translator/trace/jaegerthrift_to_protospan.go
  translator/trace/jaegerthrift_to_protospan_test.go
  translator/trace/protospan_to_jaegerthrift.go
  translator/trace/protospan_to_jaegerthrift_test.go
  translator/trace/testdata/ocproto_batch_02.json
  translator/trace/testdata/thrift_batch_no_binary_tags_01.json
  translator/trace/testdata/thrift_batch_no_binary_tags_02.json
Labels: cla: yes

#229 Allow Zipkin spans with partial LocalEndpoint info
  exporter/exporterparser/zipkin.go
  exporter/exporterparser/zipkin_test.go
Labels: cla: yes

#239 cmd/ocagent: add OpenCensus Metrics receiver + noopMetricsSink
  cmd/ocagent/main.go
  internal/config/config.go
Labels: cla: yes
