Repository census-instrumentation/opencensus-service, pull requests merged in 2019-04, with the labels that each got.

#517 Upgrade promreceiver version.
  go.mod
  go.sum
Labels: build, cla: yes

#513 Use go-cmp to show the diff for test failures.
  Makefile
  go.mod
  receiver/jaegerreceiver/jaeger_agent_test.go
  receiver/jaegerreceiver/trace_receiver_test.go
Labels: cla: yes, enhancement

#515 receiver: Add a prototype VM metrics receiver.
  cmd/ocagent/main.go
  internal/config/config.go
  receiver/vmmetricsreceiver/.nocover
  receiver/vmmetricsreceiver/doc.go
  receiver/vmmetricsreceiver/example_config.yaml
  receiver/vmmetricsreceiver/metrics_receiver.go
  receiver/vmmetricsreceiver/transform_stats_to_metrics.go
  receiver/vmmetricsreceiver/vm_metrics_collector.go
  receiver/vmmetricsreceiver/vm_metrics_constants.go
Labels: cla: yes

#521 receiver/vmmetrics: Allow to have a different process mount point.
  receiver/vmmetricsreceiver/example_config.yaml
  receiver/vmmetricsreceiver/metrics_receiver.go
  receiver/vmmetricsreceiver/vm_metrics_collector.go
Labels: cla: yes

#520 [WIP]fix aggregation type for per process stats and system stats.
  receiver/vmmetricsreceiver/vm_metrics_collector.go
  receiver/vmmetricsreceiver/vm_metrics_constants.go
Labels: cla: yes

#526 Set default project when on GCP
  README.md
  cmd/ocagent/config.yaml
  exporter/stackdriverexporter/stackdriver.go
Labels: cla: yes

#528 Add go-cmp to install-tools target
  Makefile
Labels: cla: yes

#531 Update README and k8s.yaml example
  README.md
  example/k8s.yaml
Labels: cla: yes

#529 Add profile fractions for Mutex and Block profiling
  internal/pprofserver/pprofserver.go
  internal/pprofserver/pprofserver_test.go
Labels: cla: yes
