Repository census-instrumentation/opencensus-service, pull requests merged in 2019-05, with the labels that each got.

#538 Upgrade versions of opencensus core and exporters.
  Makefile
  cmd/occollector/app/collector/telemetry.go
  exporter/jaegerexporter/jaeger.go
  exporter/opencensusexporter/opencensusexporter_test.go
  exporter/prometheusexporter/prometheus_test.go
  exporter/stackdriverexporter/stackdriver.go
  go.mod
  go.sum
  receiver/jaegerreceiver/jaeger_agent_test.go
  receiver/jaegerreceiver/trace_receiver_test.go
  receiver/prometheusreceiver/metrics_receiver_test.go
  receiver/zipkinreceiver/trace_receiver_test.go
Labels: build, cla: yes

#539 receiver/prometheues: Fix test.
  receiver/prometheusreceiver/metrics_receiver_test.go
Labels: Test-flake, cla: yes

#540 receiver/prometheus: ignore XXX_sizecache in test comparison.
  receiver/prometheusreceiver/metrics_receiver_test.go
Labels: cla: yes

#541 Add zpages to collector
  cmd/ocagent/main.go
  cmd/occollector/app/collector/collector.go
  cmd/occollector/app/collector/collector_test.go
  cmd/occollector/app/collector/empty_test.go
  demos/trace/docker-compose.yaml
  internal/zpagesserver/zpagesserver.go
  internal/zpagesserver/zpagesserver_test.go
Labels: cla: yes

#527 exporter: Add Wavefront exporter
  exporter/wavefrontexporter/.nocover
  exporter/wavefrontexporter/README.md
  exporter/wavefrontexporter/wavefront.go
  exporter/wavefrontexporter/wavefront_test.go
  go.mod
  go.sum
  internal/config/config.go
Labels: cla: yes

#544 Rename tail sampling tag as attribute
  PERFORMANCE.MD
  README.md
  cmd/occollector/app/builder/builder_test.go
  cmd/occollector/app/builder/sampling_builder.go
  cmd/occollector/app/builder/testdata/sampling_config.yaml
  cmd/occollector/app/collector/processors.go
  exporter/README.md
  internal/collector/sampling/numeric_tag_filter.go
  internal/collector/sampling/string_tag_filter.go
Labels: cla: yes

#545 Add initial OpenCensus exporter performance numbers
  PERFORMANCE.MD
Labels: cla: yes

#536 Add span attribute key mapping support (#9)
  README.md
  cmd/occollector/app/builder/processor_builder.go
  cmd/occollector/app/builder/processor_builder_test.go
  cmd/occollector/app/builder/testdata/global_attributes_all.yaml
  cmd/occollector/app/builder/testdata/global_attributes_key_mapping.yaml
  cmd/occollector/app/collector/processors.go
  cmd/occollector/app/collector/processors_test.go
  processor/attributekeyprocessor/attributekeyprocessor.go
  processor/attributekeyprocessor/attributekeyprocessor_test.go
Labels: cla: yes

#547 z-pages readme update
  README.md
Labels: cla: yes

#548 Update stackdriver exporter version.
  go.mod
  go.sum
Labels: cla: yes

#552 Update stackdriver exporter version.
  go.mod
  go.sum
Labels: build, cla: yes

#553 Fix bug in internal.CombineErrors
  internal/internal.go
  internal/internal_test.go
Labels: cla: yes

#554 receiver/vmmetrics: Simplify metrics creation.
  receiver/vmmetricsreceiver/transform_stats_to_metrics.go
  receiver/vmmetricsreceiver/vm_metrics_collector.go
  receiver/vmmetricsreceiver/vm_metrics_constants.go
Labels: cla: yes, enhancement

#549 Implement Configuration V2 models
  internal/configmodels/configmodels.go
  internal/configmodels/empty_test.go
Labels: cla: yes

#556 Add global factory registry for receivers, exporters and processors
  internal/factories/factories.go
  internal/factories/factories_test.go
Labels: cla: yes

#555 OC exporter: new configuration settings and use first available worker
  README.md
  demos/trace/oc-agent-config.yaml
  exporter/README.md
  exporter/opencensusexporter/opencensus.go
  exporter/opencensusexporter/opencensusexporter_test.go
Labels: cla: yes

#558 Fix "vet" target in makefile
  Makefile
Labels: cla: yes

#557 Implement V2 configuration loading
  go.mod
  go.sum
  internal/configv2/configv2.go
  internal/configv2/configv2_test.go
  internal/configv2/testdata/duplicate-exporter.yaml
  internal/configv2/testdata/duplicate-pipeline.yaml
  internal/configv2/testdata/duplicate-processor.yaml
  internal/configv2/testdata/duplicate-receiver.yaml
  internal/configv2/testdata/empty-config.yaml
  internal/configv2/testdata/invalid-bool-value.yaml
  internal/configv2/testdata/invalid-enabled-bool-value.yaml
  internal/configv2/testdata/invalid-enabled-bool-value2.yaml
  internal/configv2/testdata/invalid-pipeline-type-and-name.yaml
  internal/configv2/testdata/invalid-pipeline-type.yaml
  internal/configv2/testdata/invalid-receiver-name.yaml
  internal/configv2/testdata/invalid-receiver-reference.yaml
  internal/configv2/testdata/invalid-sequence-value.yaml
  internal/configv2/testdata/metric-pipeline-cannot-have-processors.yaml
  internal/configv2/testdata/missing-all-sections.yaml
  internal/configv2/testdata/missing-exporter-name-after-slash.yaml
  internal/configv2/testdata/missing-exporters.yaml
  internal/configv2/testdata/missing-pipelines.yaml
  internal/configv2/testdata/missing-processor-type.yaml
  internal/configv2/testdata/missing-processors.yaml
  internal/configv2/testdata/missing-receiver-type.yaml
  internal/configv2/testdata/missing-receivers.yaml
  internal/configv2/testdata/multiproto-config.yaml
  internal/configv2/testdata/pipeline-exporter-not-exists.yaml
  internal/configv2/testdata/pipeline-must-have-exporter.yaml
  internal/configv2/testdata/pipeline-must-have-exporter2.yaml
  internal/configv2/testdata/pipeline-must-have-processors.yaml
  internal/configv2/testdata/pipeline-must-have-receiver.yaml
  internal/configv2/testdata/pipeline-processor-not-exists.yaml
  internal/configv2/testdata/unknown-exporter-type.yaml
  internal/configv2/testdata/unknown-processor-type.yaml
  internal/configv2/testdata/unknown-receiver-type.yaml
  internal/configv2/testdata/valid-config.yaml
Labels: cla: yes

#561 Upgrade dependency versions.
  go.mod
  go.sum
Labels: build, cla: yes

#563 Upgrade Stackdriver Exporter version.
  go.mod
  go.sum
Labels: build, cla: yes

#560 Add grpc server configs to OC receiver
  README.md
  cmd/occollector/app/builder/builder.go
  cmd/occollector/app/builder/builder_test.go
  cmd/occollector/app/builder/testdata/oc_keepalive_config.yaml
  example/k8s.yaml
  internal/collector/opencensus/.nocover
  internal/collector/opencensus/receiver.go
  internal/collector/opencensus/receiver_test.go
  receiver/README.md
Labels: cla: yes
